default: &default
  adapter: postgresql
  encoding: unicode  
  pool: 5
  timeout: 5000
  username: rails1
  password: qwerty123
  host: localhost

development:
  <<: *default
  database: medss_dev
test:
  <<: *default
  database: medss_test

  production:
  <<: *default
  database: medss_prod